### ISSUE TITLE
Drag an item inside the dropzone but not directly on top of another item not working.

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#47]
Hi! Great work on v2 so far!

Just to clarify the issue: if you try to drag an item **between** other 2 items (in the same list), the drop does not happen. (So in order to work, the cursor must be above another item when released.)

I don't know if its a v2 specific behaviour, however I don't remember it from before. 
The issue happens in the demo site too.

Thanks.

**Comment by Postlagerkarte** [comment]
Hi @kristof12345  - thank you for testing & and the feedback!

I fixed the issue and updated the demo page.

**Comment by buzzer83** [comment]
Hi @Postlagerkarte,
I already wrote to you about using v1, very good. I would like to update my software with this version (2), but I believe this bug is still present in the demo too (Part3 - twozones), right?

**Comment by kristof12345** [comment]
Hi @Postlagerkarte After doing some testing, I realized that if you drag an item between others (like in the original post):

- It still does not work if they're in the same list.

- It works, but adds the item to the end of the destination list if they're in separate lists.

The same issue in the demo site and local app. 
Version: 2.0.2

**Comment by Postlagerkarte** [comment]
Yes, seems another bug slipped in.  

Hope it works now - please check the demo page again :

![test_twzones](https://user-images.githubusercontent.com/8482283/89729221-b39fc100-da33-11ea-8604-b6d3de0e447b.gif)

**Comment by kristof12345** [comment]
Yes now it works in the demo. Thanks for the quick response.
